// Generated by CoffeeScript 1.4.0
(function() {
  var example, tts;

  require('coffee-script');

  tts = require('./node-tts-api');

  example = "Hello World";

  tts.getSpeech(example, function(error, link) {
    return console.log(link);
  });

}).call(this);
